# This workflow will install Python dependencies, lint and run tests.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  pre-commit_linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          submodules: true  # submodules needed, otherwise mypy gets confused about ignoring them
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install pre-commit dependencies
        run: |
          pip install pre-commit==4.2.0
          pre-commit install
      - name: Run pre-commit checks
        run: pre-commit run --all-files

  delta_crit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          submodules: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
          pip install -e ./third_party/commonroad-crime
      - name: pytest for delta_crit
        run: |
          cd delta_crit
          python -m pytest
